### ISSUE TITLE
I'm seeing some issues like `Node is not a constant`

### ISSUE THREAD

**Issue by danillos** [lekemula/solargraph-rspec#7]
```
2024-07-16T17:58:53.058 helix_lsp::transport [ERROR] solargraph err <- "[WARN] [RSpec] Error processing /Users/danillos/Work/file_spec.rb: Node is not a constant\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-rspec-0.3.0/lib/solargraph/rspec/spec_walker/full_constant_name.rb:11:in `from_ast'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-rspec-0.3.0/lib/solargraph/rspec/spec_walker/full_constant_name.rb:17:in `from_ast'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.
0/gems/solargraph-rspec-0.3.0/lib/solargraph/rspec/spec_walker/full_constant_name.rb:17:in `from_ast'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-rspec-0.3.0/lib/solargraph/rspec/spec_walker/full_constant_name.rb:17:in `from_ast'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-rspec-0.3.0/lib/solargraph/rspec/spec_walker/full_constant_name.rb:17:in `from_ast'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-rspec-0.3.0/lib/solargraph/rspec/spec_walker/rspec_context_namespace.rb:17:in `from_block_ast'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-rspec-0.3.0/lib/solargraph/rspec/spec_walker.rb:201:in `block in each_context_block'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-rspec-0.3.0/lib/solargraph/rspec/spec_walker.rb:185:in `each_block'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-rspec-0.3.0/lib/solargraph/rspec/spec_walker.rb:189:in `block in each_block'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-rspec-0.3.0/lib/solargraph/rspec/spec_walker.rb:189:in `each'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-rspec-0.3.0/lib/solargraph/rspec/spec_walker.rb:189:in `each_block'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-rspec-0.3.0/lib/solargraph/rspec/spec_walker.rb:196:in `each_context_block'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-rspec-0.3.0/lib/solargraph/rspec/spec_walker.rb:100:in `walk!'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-rspec-0.3.0/lib/solargraph/rspec/convention.rb:126:in `local'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/convention.rb:29:in `block in for_local'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/2.7.0/set.rb:328:in `each_key'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/2.7.0/set.rb:328:in `each'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/convention.rb:28:in `for_local'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/source_map.rb:32:in `initialize'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/source_map.rb:156:in `new'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/source_map.rb:156:in `map'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/library.rb:530:in `maybe_map'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/library.rb:58:in `block in attach'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/library.rb:50:in `synchronize'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/library.rb:50:in `attach'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/language_server/host/dispatch.rb:85:in `block in implicit_library_for'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/language_server/host/dispatch.rb:83:in `each'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/language_server/host/dispatch.rb:83:in `implicit_library_for'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/language_server/host/dispatch.rb:42:in `library_for'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/language_server/host.rb:532:in `definitions_at'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/language_server/message/text_document/definition.rb:14:in `code_location'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/language_server/message/text_document/definition.rb:8:in `process'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/language_server/host.rb:112:in `receive'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/language_server/host/message_worker.rb:53:in `tick'\n"
2024-07-16T17:58:53.059 helix_lsp::transport [ERROR] solargraph err <- "/Users/danillos/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/solargraph-0.49.0/lib/solargraph/language_server/host/message_worker.rb:44:in `block in start'\n"

```

**Comment by lekemula** [comment]
Thanks @danillos for reporting this issue and including the logs. Could you please provide a minimal reproducible RSpec file so that I can better investigate what could be causing this?

Divide-and-conquer from top-down of spec contexts and checking whether the log appears is the most efficient way.
Also, it doesn't need to be exact code, the syntax is the important bit here, so feel free to obfuscate the contexts and example descriptions.

Thank you in advance!

**Comment by lekemula** [comment]
@danillos, do you still encounter this issue?
